sudo: false
dist: trusty

language: php

notifications:
  email: never

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: WP_VERSION=trunk RUN_PHPCS=1 RUN_CODE_COVERAGE=1
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest


before_script:
  - if [[ ${RUN_CODE_COVERAGE} ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
      chmod +x coveralls.phar
      mkdir -p build/logs
    else
      phpenv config-rm xdebug.ini
    fi
  - composer install --prefer-dist --no-scripts
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - WP_MULTISITE=0 ./vendor/bin/phpunit
  - |
    if [[ ${RUN_CODE_COVERAGE} ]]; then
      WP_MULTISITE=0 ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    else
      WP_MULTISITE=0 ./vendor/bin/phpunit
    fi
  - |
    if [[ ${RUN_PHPCS} == 1 ]]; then
      ./vendor/bin/phpcs
    fi
