sudo: false
dist: trusty

language: php

notifications:
  email: never

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: WP_VERSION=trunk
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest


before_script:
  - composer install --prefer-dist --no-scripts
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - WP_MULTISITE=0 ./vendor/bin/phpunit
